# Generated by Django 2.1 on 2020-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201028_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
