# Generated by Django 2.1 on 2020-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_history_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=32)),
                ('mid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('srcFilePath', models.CharField(max_length=32)),
                ('destFilePath', models.CharField(max_length=32)),
                ('thumnail', models.CharField(default='', max_length=32)),
                ('result', models.CharField(max_length=32)),
                ('category', models.CharField(default=1, max_length=32)),
                ('create_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collect',
                'verbose_name_plural': 'Collect',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='thumnail',
            field=models.CharField(default='', max_length=32),
        ),
    ]
