# Generated by Django 2.1 on 2020-11-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201028_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Member'},
        ),
        migrations.AlterModelTable(
            name='collect',
            table='collect',
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
