# Generated by Django 2.1 on 2020-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201117_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
