# Generated by Django 2.1 on 2020-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201117_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='destFilePath',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='collect',
            name='srcFilePath',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='collect',
            name='thumnail',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='history',
            name='destFilePath',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='history',
            name='srcFilePath',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='history',
            name='thumnail',
            field=models.CharField(default='', max_length=256),
        ),
    ]
